name: Minify HTML and CSS in place

on:
  push:
    branches:
      - main

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip minify]')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install minifiers
        run: npm install -g html-minifier-terser csso-cli

      - name: Minify HTML files (root) excluding Liber_de_Creaturis__religio.html
        run: |
          for f in *.html; do
            if [ "$f" != "Liber_de_Creaturis__religio.html" ]; then
              html-minifier-terser --collapse-whitespace --remove-comments --minify-css true --minify-js true "$f" -o "$f"
            else
              echo "Skipping $f"
            fi
          done

      - name: Minify CSS files (root)
        run: |
          shopt -s nullglob
          files=( *.css )
          if [ ${#files[@]} -gt 0 ]; then
            for f in "${files[@]}"; do
              csso "$f" --output "$f"
            done
          else
            echo "No CSS files found in root"
          fi

      - name: Minify CSS files in "Css files" folder recursively
        run: |
          find "Css files" -type f -name "*.css" -exec csso {} --output {} \;

      - name: Commit and push minified files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add *.html *.css "Css files"/*.css
          git commit -m "Minify HTML and CSS [skip minify]" || echo "No changes to commit"
          git push
