name: Ping Supabase

on:
  schedule:
    - cron: "*/5 * * * *" # toutes les 5 minutes
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Appel ping Supabase
        run: |
          curl -X POST "https://crdzcgqrakjjdujhqmic.supabase.co/rest/v1/ping" \
          -H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNyZHpjZ3FyYWtqamR1amhxbWljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNTQ2MDAsImV4cCI6MjA2MjgzMDYwMH0.F32OEbuWNwRAbmiaAK5WMMvCfopXc6pIvh9CgX0sLY8" \
          -H "Content-Type: application/json" \
          -d '{"chat_uid": "anonyme"}'
